schroot: Transform mtab for chroot
Rather than link /etc/mtab to /proc/self/mounts as we were doing, translate
the entries in /proc/mounts to account for the chroot environment and save
that as /proc/mtab. This will allow tools like mount and df to work correctly
within the chroot.

Signed-off-by: Ian Munsie <darkstarsword@gmail.com>

diff --git a/schroot b/schroot
--- a/schroot
+++ b/schroot
@@ -104,8 +104,13 @@ setup()
 		echo "Copying $file into $chroot/$file..."
 		cp -f "$file" "$chroot/$file" || die "Failed to copy $file"
 	done
-	echo "Linking $chroot/etc/mtab to /proc/self/mounts"
-	ln -sf /proc/self/mounts "$chroot/etc/mtab" || die "Failed to link /etc/mtab"
+
+	echo "Updating $chroot/etc/mtab..."
+	rm $chroot/etc/mtab
+	sub_bindroot=$(echo $bindroot | sed 's/\//\\\//g')
+	sub_chroot=$(echo $chroot | sed 's/\//\\\//g')
+	sed "s/^\(\S*\) \(\S*\) /\1 $sub_bindroot\2 /g; s/^\(\S*\) $sub_bindroot$sub_chroot/\1 /" </proc/mounts > "$chroot/etc/mtab" || die "Failed to update $chroot/etc/mtab"
+
 	echo "Updating $chroot/etc/hosts entry for $(hostname)..."
 	tmp=`mktemp /tmp/tmp.XXXXXXXXXX`
 	grep -v "^127.0.0.1 $(hostname)$" "$chroot/etc/hosts" > "$tmp"
